source = ~/.cache/wal/colors-hyprland.conf

plugin {
    hyprtrails {
        color = $color4
    }

    hyprwinwrap {
        # class is an EXACT match and NOT a regex!
        class = kitty-bg
        # you can also use title
        title = kitty-bg
        # you can add the position of the window in a percentage
        pos_x = 25
        pos_y = 30
        # you can add the size of the window in a percentage
        size_x = 40
        size_y = 70
    }

    hyprbars {

        # bar_color = $background
        # bar_color = rgba(23, 25, 34, 0.85)
        bar_color = $color0
        bar_blur = true

        bar_height = 42

        col.text = $foreground
        bar_text_size = 14
        bar_text_align = center
        bar_buttons_alignment = right
        bar_text_font = Adwaita Sans Bold
        icon_on_hover = true
        bar_button_padding = 12
        bar_padding = 16
        bar_precedence_over_border = true
        bar_part_of_window = true
        # hyprbars-button = $color1, 18, , hyprctl dispatch killactive, $color0
        # hyprbars-button = $color3, 18, , hyprctl dispatch fullscreen 2, $color0
        # hyprbars-button = $color2, 18, , hyprctl dispatch togglefloating, $color0
        
        hyprbars-button = $color1,20,, hyprctl dispatch killactive, $background
        hyprbars-button = $color3,20,, hyprctl dispatch fullscreen 2, $background
        hyprbars-button = $color2,20,, hyprctl dispatch togglefloating, $background

    }
    borders-plus-plus {
        add_borders = 0 # 0 - 9

        # you can add up to 9 borders
        col.border_1 = $color7
        col.border_2 = $color8

        # -1 means "default" as in the one defined in general:border_size
        border_size_1 = 10
        border_size_2 = 3

        # makes outer edges match rounding of the parent. Turn on / off to better understand. Default = on.
        natural_rounding = on
    }
    hyprexpo {
        columns = 3
        gap_size = 16
        bg_col = $background
        workspace_method = first 1
        enable_gesture = true # laptop touchpad, 4 fingers
        gesture_distance = 100 # how far is the "max"
        gesture_positive = false # positive = swipe down. Negative = swipe up.
        gesture_fingers = 3
    }
   }
