exec-once = systemctl --user start hyprland-session.target
exec-once = wl-clipboard
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent
exec-once = sudo mount -a
exec-once = ~/publicdots/scripts/hyprportal.sh
exec-once = hypridle
exec-once = swww-daemon
exec-once = hyprpm reload -n
# exec-once = gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Ice
# exec-once = gsettings set org.gnome.desktop.interface color-scheme prefer-dark

# exec = gsettings set org.gnome.desktop.interface gtk-theme ""   # for GTK3 apps
# exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-light"   # for GTK4 apps

env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps



exec-once = hyprpm enable hyprbars
exec = brightnessctl --device='tpacpi::kbd_backlight' set 1
exec-once = killall waybar
exec-once = sleep 0.1 && waybar
exec-once = killall agsv1
exec-once = killall ags
exec-once = ~/publicdots/scripts/spotify-notify.py &
# exec-once = zen-twilight
# exec-once = slack
# exec-once = spotify
#exec = sleep 0.2 && agsv1
#exec = brightnessctl s 75%
#exec = brightnessctl --device='tpacpi::kbd_backlight' set 1
exec = ~/publicdots/scripts/swayncreload.sh && swaync
exec-once = ~/dots/.config/hypr/scripts/run-overlay.sh

# exec-once = ~/publicdots/scripts/nwg-dock-start.sh
